baseURL = "https://example.com/"
theme = "hugo-theme-meme"
title = "MemE"
# https://en.wikipedia.org/wiki/Language_localisation
# https://www.zhihu.com/question/21980689
languageCode = "en-US"
copyright = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)"

defaultContentLanguage = "en-us"
defaultContentLanguageInSubdir = false

enableGitInfo = false

pluralizeListTitles = false

summaryLength = 42

enableRobotsTXT = true

pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "linenos=table"

enableEmoji = true

footnoteReturnLinkContents = "↩"

paginate = 3

[related]
threshold = 80
includeNewer = true
toLower = true
[[related.indices]]
name = "series"
weight = 100
[[related.indices]]
name = "categories"
weight = 100
[[related.indices]]
name = "tags"
weight = 95
[[related.indices]]
name = "keywords"
weight = 90
[[related.indices]]
name = "date"
weight = 10
pattern = "2006"

# [frontmatter]
# lastmod = ["lastmod", ":git", ":fileModTime", ":default"]

[blackfriday]
smartypants = false
fractions = false
hrefTargetBlank = true
extensionsmask = ["hardLineBreak", "backslashLineBreak"]

[languages.en-us]
languageName = "English"
contentDir = "content/en"
weight = 1
languageCode = "en-US"
title = "Hugo Theme MemE"
copyright = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)"

[languages.zh-cn]
languageName = "中文"
contentDir = "content/zh"
weight = 2
languageCode = "zh-CN"
hasCJKLanguage= true
title = "Hugo 主题 MemE"
copyright = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh)"
[[languages.zh-cn.menu.main]]
url = "/zh-cn/"
name = "首页"
weight = 1
pre = "internal"
post = "home"
identifier = "home"
[[languages.zh-cn.menu.main]]
url = "/zh-cn/archives/"
name = "归档"
weight = 2
pre = "internal"
post = "archive"
identifier = "archives"
[[languages.zh-cn.menu.main]]
url = "/zh-cn/posts/"
name = "文章"
weight = 3
pre = "internal"
post = "wpexplorer"
identifier = "posts"
[[languages.zh-cn.menu.main]]
url = "/zh-cn/series/"
name = "专栏"
weight = 4
pre = "internal"
post = "grav"
identifier = "series"
[[languages.zh-cn.menu.main]]
url = "/zh-cn/categories/"
name = "分类"
weight = 5
pre = "internal"
post = "th"
identifier = "categories"
[[languages.zh-cn.menu.main]]
url = "/zh-cn/tags/"
name = "标签"
weight = 6
pre = "internal"
post = "tags"
identifier = "tags"
[[languages.zh-cn.menu.main]]
url = "/zh-cn/about/"
name = "关于"
weight = 7
pre = "internal"
post = "user-circle"
identifier = "about"
[[languages.zh-cn.menu.socials]]
url = "https://github.com/"
name = "GitHub"
weight = 1
pre = "external"
identifier = "github"
[[languages.zh-cn.menu.socials]]
url = "https://twitter.com/"
name = "Twitter"
weight = 2
pre = "external"
identifier = "twitter"
[[languages.zh-cn.menu.socials]]
url = "https://www.spotify.com/"
name = "Music"
weight = 3
pre = "external"
identifier = "music"
[[languages.zh-cn.menu.links]]
url = "/zh-cn/"
name = "HOME"
weight = 1
pre = "internal"
identifier = "home"
[[languages.zh-cn.menu.links]]
url = "/zh-cn/series/"
name = "专栏"
weight = 2
pre = "internal"
identifier = "series"
[[languages.zh-cn.menu.links]]
url = "/zh-cn/atom.xml"
name = "Feed"
weight = 3
pre = "external"
identifier = "feed"
[languages.zh-cn.params]
lineHeight = 2
fontSize = 16
postWidth = 36
enableSmallCap = false
enableEmphasisPoint = true
enableChinesePunctuationGlyphCorrection = true
enableJustify = true
fontFamilyTitle = "'Cinzel Decorative', 'Noto Serif SC', serif"
fontFamilyHeadings = "'Cinzel Decorative', 'Noto Serif SC', serif"
fontFamilyCode = "'Source Code Pro', 'Noto Serif SC', monospace"
fontFamilyBody = "'EB Garamond', 'Noto Serif SC', serif"
fontsLink = 'https://fonts.googleapis.com/css?family=EB+Garamond:400,400i,500,700,700i|Noto+Serif+SC:400,500,700|Source+Code+Pro:400,400i,700,700i|Cinzel+Decorative:700&display=swap&subset=chinese-simplified'

# uglyURLs = true

[permalinks]
# life = "/:sections/:slug/"
# tech = "/:sections/:slug/"
categories = "/categories/:slug/"
tags = "/tags/:slug/"
series = "/series/:slug/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[mediaTypes."application/atom+xml"]
suffixes = ["xml"]

[outputFormats.SectionsAtom]
mediaType = "application/atom+xml"
baseName = "atom"

[outputFormats.SectionsRSS]
mediaType = "application/rss+xml"
baseName = "rss"
# [outputFormats.NoUglyHTML]
# mediaType = "text/html"
# noUgly = "true"
# [outputFormats.NoUglyRSS]
# mediaType = "application/rss+xml"
# noUgly = "true"
# [outputFormats.NoUglyAtom]
# mediaType = "application/atom+xml"
# baseName = "atom"
# noUgly = "true"

# [outputs]
# page = ["HTML"]
# home = ["HTML", "Atom", "RSS", "SectionsAtom", "SectionsRSS"]
# section = ["NoUglyHTML", "NoUglyRSS", "NoUglyAtom"]
# # Not working below v0.57.0, see: https://github.com/gohugoio/hugo/issues/4528
# taxonomyTerm = ["NoUglyHTML", "NoUglyRSS"]
# taxonomy = ["NoUglyHTML", "NoUglyRSS"]

[outputs]
page = ["HTML"]
home = ["HTML", "SectionsAtom", "SectionsRSS"]
section = ["HTML"]
# Not working below v0.57.0, see: https://github.com/gohugoio/hugo/issues/4528
taxonomyTerm = ["HTML"]
taxonomy = ["HTML"]

[author]
name = "MemE"
email = "meme@example.com"
# Your description, Markdown supported, this theme noly
motto = "You can’t spell aWEsoME without MEME!"
# Your avatar, URL, this theme noly
avatar = "/icons/apple-touch-icon.png"
# URL, this theme noly, Default: baseURL
website = "https://github.com/reuixiy/hugo-theme-meme"
twitter = ""
facebook = ""

# RSS & Atom limit
[services.rss]
limit = -1

[[menu.main]]
url = "/"
name = "Home"
weight = 1
pre = "internal"
post = "home"
identifier = "home"

[[menu.main]]
url = "/archives/"
name = "Archives"
weight = 2
pre = "internal"
post = "archive"
identifier = "archives"

[[menu.main]]
url = "/posts/"
name = "Posts"
weight = 3
pre = "internal"
post = "wpexplorer"
identifier = "posts"

[[menu.main]]
url = "/series/"
name = "Series"
weight = 4
pre = "internal"
post = "grav"
identifier = "series"

[[menu.main]]
url = "/categories/"
name = "Categories"
weight = 5
pre = "internal"
post = "th"
identifier = "categories"

[[menu.main]]
url = "/tags/"
name = "Tags"
weight = 6
pre = "internal"
post = "tags"
identifier = "tags"

[[menu.main]]
url = "/about/"
name = "About"
weight = 7
pre = "internal"
post = "user-circle"
identifier = "about"

# [[menu.home]]
# url = "/life/"
# weight = 1
# pre = "internal"
# post = "grav"
# identifier = "life"

# [[menu.home]]
# url = "/tech/"
# weight = 2
# pre = "internal"
# post = "wpexplorer"
# identifier = "tech"

# [[menu.home]]
# url = "/about/"
# weight = 3
# pre = "internal"
# post = "user-circle"
# identifier = "about"

# [[menu.home]]
# url = "/life/"
# name = "Life"
# weight = 1
# pre = "internal"
# identifier = "life"

# [[menu.home]]
# url = ""
# name = "Telegram"
# weight = 2
# pre = "external"
# identifier = "telegram"

# [[menu.home]]
# url = "/atom.xml"
# name = "Feed"
# weight = 3
# pre = "external"
# identifier = "feed"

[[menu.socials]]
url = "https://github.com/"
name = "GitHub"
weight = 1
pre = "external"
identifier = "github"

[[menu.socials]]
url = "https://twitter.com/"
name = "Twitter"
weight = 2
pre = "external"
identifier = "twitter"

[[menu.socials]]
url = "https://www.spotify.com/"
name = "Music"
weight = 3
pre = "external"
identifier = "music"

[[menu.links]]
url = "/"
name = "HOME"
weight = 1
pre = "internal"
identifier = "home"

[[menu.links]]
url = "/series/"
name = "Series"
weight = 2
pre = "internal"
identifier = "series"

[[menu.links]]
url = "/atom.xml"
name = "Feed"
weight = 3
pre = "external"
identifier = "feed"

[params]
enableHeader = true
displayHeaderInHome = true

enableMenu = true
displayMenuInHome = true

# Use for Header, If true, Please put your SVG brand image to `SVG.toml`.
# If false, will use your Site Title as fallback.
# Unit: px
siteBrandSVG = true
siteBrandSVGWidth = 250
siteBrandSVGHeight = 100
siteBrandSVGFill = "#fff"

# Unit: em
siteBrandFontSize = 5
siteBrandFontColor = "#fff"

# siteBrandBackgroundColor = "hsl(240, 8%, 12%)"
siteBrandBackgroundImage = "linear-gradient(90deg, #f79533 0, #f37055 15%, #ef4e7b 30%, #a166ab 44%, #5073b8 58%, #1098ad 72%, #07b39b 86%, #6dba82 100%)"

# poetry, footage, posts, page
homeLayout = "posts"

# Layout poetry settings
# Markdown supported
homePoetry = []
# Unit: em
homeLinksPadding = 1

# Layout footage settings
homePoster = ""
homeVideoWebm = ""
homeVideoMp4 = ""
homeLogo = ""
homeLogoLink = ""
homeTitle = ""
homeMotto = ""
homeDescription = ""
homeKeywords = ""
homeLinksDelimiter = ""

# URL, For JSON-LD, Twitter Cards, Open Graph
siteLogo = "/icons/apple-touch-icon.png"
# For HTML meta
siteDescription = "MemE is a powerful and highly customizable GoHugo blog theme."
# If not set, will use site’s all taxonomy terms as default
siteKeywords = []
# Keep this format, change the number
siteCreatedTime = "1969-07-20T20:17:43+00:00"
# If you enable `twitterCards`, then add your Twitter username
siteTwitter = ""
# If you enable `openGraph`, then add your Facebook username
siteFacebook = ""

# Category
# sections or categories
# Note: You must delete `categories` in `taxonomies` if you set `sections`.
categoryBy = "categories"

# Categories Page
# Note: You can NOT disable tree if you set categoryBy equal to `sections`.
enableTree = true
displayPosts = true
displayPostsCount = true

# Tags
enableTagCloud = true
fontUnit = "em"
largestFontSize = 2.5
smallestFontSize = 1

# Unit: em
# You can leave it empty ("") to fallback to default value: 42
listWidth = 30
displayListTitle = true
# https://gohugo.io/functions/format/
listDateFormat = "January 2"
# left / right
listDatePosition = "right"
groupByMonth = true
chineseZodiac = true
i18nYear = true
i18nMonth = true

# Taxonomy List
displayTaxonomyTermCount = true

# Override Hugo’s default value
mainSections = ["posts"]

# Post Sections
postSections = ["posts", "poetry"]

# Feed
feedSections = ["posts"]
# If `true`, will add content to Atom; If `false`, won’t.
# Note: By default, will add summary to Atom as `summary`,
# and if Front Matter have a description, description
# will override summary as `summary`
includeContent = true

# Dark Mode
enableDarkMode = true
defaultTheme = "light"
# Note: If true and enableDarkMode equal to `true`,
# users can still get Dark Mode if their device’s system
# has enabled Dark Mode (`prefers-color-scheme: dark`).
hideThemeToggle = false
hideThemeToggleInHome = false
# Useful for black and white images on a white background.
# Bad for color images. I suggest you set `true` in post’s
# Front Matter instead of here, unless all your images are
# black and white on a white background. Also, you can set
# `true` here and set `false` in Front Matter which will
# override what you have set here.
darkImage = true

# Web App
# https://realfavicongenerator.net/
# Keep android-chrome-512x512.png, apple-touch-icon.png, mstile-150x150.png,
# safari-pinned-tab.svg, favicon.ico, site.webmanifest and delete others
# Move to ~/blog/static/icons/
# Move favicon.ico site.webmanifest to ~/blog/static/
# Rename site.webmanifest to manifest.json
# See https://github.com/w3c/manifest/issues/689
# See https://github.com/OneSignal/OneSignal-Website-SDK/issues/332
# Check and Modify manifest.json (/icons path)
themeColor = "#fff"
themeColorDark = "#000"
safariMaskColor = "#2a6df4"
msApplicationTileColor = "#fff"

# Head Meta, SEO & Social Discovery
# Note that you must set openGraph to `true` if you set twitterCards to `true`,
# or your Twitter Cards info would be incomplete.
jsonLD = true
openGraph = true
twitterCards = true
autoDetectImages = true

# InstantClick
enableInstantClick = true

enableServiceWorker = false

# I suggest you set `katex: true` in post’s Front Matter instead of here
enableKaTeX = false

enableComments = false
enableDisqus = false
disqusShortname = ""

enableGoogleAnalytics = false
# `gtag` or `analytics`
trackingCodeType = "gtag"
trackingID = ""

googleSiteVerification = ""

# https://developers.facebook.com/apps/
# Used for Open Graph
facebookAppID = ""

# Post

# Unit: second
duration = 0.5

# HSL color
primaryColorLight = "220, 90%, 56%"
primaryColorDark = "349, 75%, 51%"

# Unit: em
# You can leave it empty ("") to fallback to default value: 42
postWidth = 32

# Do NOT Change this value!
# If one post is not original, set in that post’s Front Matter.
original = true

# Post Description
displayPostDescription = true

# Post Meta
enablePostMeta = true
# Works for home layout `posts` only
enablePostMetaInHome = true
postMetaDateFormat = "January 2, 2006"
displayPublishedDate = true
publishedDateIcon = "calendar-alt"
displayModifiedDate = true
modifiedDateIcon = "calendar-check"
# Note that it will not display if the date is zero (not set).
displayExpiredDate = true
expiredDateIcon = "calendar-times"
displayCategory = true
categoryIcon = "folder"
categoryDelimiter = "/"
displayWordCount = true
wordCountIcon = "pencil-alt"
displayReadingTime = true
readingTimeIcon = "clock"

# Table of Contents
enableTOC = true
displayTOCTitle = true
linkHeadingsToTOC = true

# Headings Anchor / Section Sign (Add section sign before headings)
enableHeadingsAnchor = true
# RegEX format, Defaut: 1-6 (1|2|3|4|5|6), h1-h6
headingsOpt = "1-6"
# `anchorIcon` has a higher priority than `anchorSymbol`
# Default: §
anchorSymbol = "#"
anchorIcon = "link"
enableAnchorLink = true
enableAnchorAutoHide = true

# Image / Video
# If true, will replace `title` with caption.
enableCaption = true
captionPrefix = "◎ "

# Image Hosting
# Only support absolute URLs relative to root,
# eg: /../../*.jpg
enableImageHost = false
imageHostURL = "https://example.com/"
# Use host URL for head meta tags also
headAlso = false

# Video Hosting
# Only support absolute URLs relative to root,
# eg: /../../*.mp4
enableVideoHost = false
videoHostURL = "https://example.com/"

# Footnote
# Footnote Ref with Square Brackets `[]`
squareBrackets = true
# If true, will replace `footnoteReturnLinkContents` with icon.
footnoteReturnLinkIcon = "angle-up"
# If true, the automatically added `<hr />` will be deleted.
# (In fact, the separator you added will be removed. This
# will be very useful if you prefer to add `---` to separate
# the content from the footnote in the Markdown file.)
insertHrBySelf = true

# Markdown
# New Markdown Syntax: Emphasis Point `..text..`
enableEmphasisPoint = false

# Typography
# Fonts, Unit: px
fontSize = 20
# Unitless values: use this number multiplied by the element’s font size
# Apply to post paragraph & toc only
lineHeight = 1.618

# Any value is not set, fallback to `fontFamilyBody` it will.
# If you use SVG as your Site Brand, then leave this value empty.
fontFamilySiteBrand = ""
fontFamilyMenu = ""
fontFamilyTitle = "Comfortaa, sans-serif"
fontFamilyHeadings = "Comfortaa, sans-serif"
fontFamilyCode = "'Source Code Pro', monospace"
fontFamilyQuote = ""
fontFamilyTOC = ""
fontFamilyCaption = ""
fontFamilyFooter = ""
fontFamilyBody = "'IBM Plex Serif', serif"

# https://fonts.google.com/
fontsLink = 'https://fonts.googleapis.com/css?family=IBM+Plex+Serif:400,400i,500,700,700i|Source+Code+Pro:400,400i,700,700i|Comfortaa:700&display=swap'

enableChinesePunctuationGlyphCorrection = false

# Post headings and contents title
enableSmallCap = true

# Post first paragraph
enableDropCap = true
# Every paragraph after `<hr />` or `---` in Markdown
enableDropCapAfterHr = false
deleteHrBeforeDropCap = false

enableParagraphIndent = true
# margin or indent, globe setting, Front Matter: indent
paragraphStyle = "margin"

enableJustify = false

# Post Copyright
enablePostCopyright = true
displayPostCopyright = true

enablePostUpdatedBadge = true
displayUpdatedBadge = true
enableBadgeTitle = true
badgeTitlePrefix = "Updated @ "

enablePostGitInfo = false
displayPostGitInfo = false
repoURL = "https://github.com/reuixiy/meme-test"
# or https://github.com/reuixiy/meme-test/edit/master
repoEditURL = "https://github.com/reuixiy/meme-test/blob/master"
gitIcon = "code-branch"
displayCommitHash = true
displayCommitMessage = true
msgIcon = "info"
displayFeedback = true
feedbackIcon = "question"
feedbackText = "Feedback"
displayEditLink = true
editIcon = "edit"
editText = "Edit Me?"

# Related Posts
enableRelatedPosts = true
displayRelatedPosts = true
relatedPostsNumber = 5
relatedPostsIcon = "plus-circle"

# Post tags
enablePostTags = true
postTagsIcon = "tag"

# Post minimal footer
enableMinimalFooter = true
enableAboutPageMinimalFooter = true

# Post nav
# Note: Designed from a spatial perspective rather than
#       a time perspective like most other themes do.
#       Therefore, you will get a newer post if you click
#       prev on the left; you will get a older post if
#       you click next on the right.
enablePostNav = true
postNavInSection = false

# Syntax Highlight
enableHighlight = true

# Back to Top
enableBackToTop = true
backToTopIcon = "arrow-up"
displayBackToTopInHome = true

# Footer
# Note: Home layout `poetry`, `footage`, and 404 page have no footer.
enableFooter = true
displayCopyrightSymbol = true
displaySiteCreatedYear = true
iconBetweenYearAndAuthor = "heart"
iconColor = "#f06292"
iconAnimation = true
displayPoweredBy = true
displaySiteCopyright = true
customFooter = ""

# Multilingual
enableLangToggle = true
# Display LangToggle only when content is translated
autoHideLangToggle = true
hideLangToggleInHome = false

# Style & Script
enableFingerprint = true

# 404
fofPoster = ""
fofVideoWebm = ""
fofVideoMp4 = ""
